name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [1] # Uses 2 parallel instances
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Ping API
        uses: Leocardoso94/is-my-site-up@v1.2
        with:
          site: https://samuraibs-api-papito.fly.dev
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install-command: yarn install
          wait-on: 'https://samuraibs-web-papito.fly.dev'
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true # Runs test in parallel using settings above
          group: 'UI - Chrome'
          spec: cypress/e2e/*
	env:    
          TZ: America/Sao_paulo
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
