# This is a basic workflow to help you get started with Actions

name: Firefox UI Tests

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      specs:
        description: 'Run ALL or unique spec'
        default: cypress/e2e/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  chrome-ui-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Ping API (heroku)
        uses: Leocardoso94/is-my-site-up@v1.2
        with:
          site: https://samuraibs-api-papito.fly.dev

      - name: 'UI Tests - Firefox'
        uses: cypress-io/github-action@v6
        with:
          # we have already installed all dependencies above
          install-command: yarn install
          wait-on: 'https://samuraibs-web-papito.fly.dev'
          wait-on-timeout: 120
          browser: firefox
          record: true
          parallel: true
          group: 'UI - Firefox'
          spec: ${{ github.event.inputs.specs }}
        env:
          TZ: America/Sao_Paulo
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
